name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master
      - gh-pages
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.5'
          bundler-cache: true
      - uses: actions/configure-pages@v5
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
      - uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: github-pages
    steps:
    - uses: actions/deploy-pages@v4

  html-link-check:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check html
      run: make check
