name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master
      - gh-pages
  workflow_dispatch:
  
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.4.0
        env:
          JEKYLL_PAT: ${{ github.actor }}:${{ github.token }}
