name: Check HTML links

on: push

jobs:
  markdown-link-check:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install any new ruby packages
      run: make install

    - name: Dependencies
      run: make update

    - name: Check html
      run: make check
