name: Check HTML links

on: push

jobs:
  markdown-link-check:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
      with:
        ruby-version: '3.1'

    - name: Install any new ruby packages
      run: make install

    - name: Dependencies
      run: make update

    - name: Build site
      run: make build

    - name: Check html
      run: make check
